branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - make docs

deploy:
  provider: pages
  cleanup: true
  strategy: git
  local_dir: docs/html
  token: $GH_REPO_TOKEN
  on:
    branch: master
